In [7]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

ERROR: Error in parse(text = x, srcfile = src): <text>:5:8: unexpected symbol
4: 
5: import numpy
          ^


In [ ]:
2+3

In [ ]:
6/3

In [ ]:
(3*8)/(2*3)

In [ ]:
log(12)
sqrt(121)

In [71]:
x<-1:15
cat(x)
cat('mean of x is',mean(x))
cat('median of x is ',median(x))
cat('varaince of x is ',var(x))
cat('standars deviation of x is ',sd(x))

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15mean of x is 8median of x is  8varaince of x is  20standars deviation of x is  4.472136

In [16]:
x<-1:15
cat(x,'\n')
cat('mean of x is',mean(x),'\n')
cat('median of x is ',median(x),'\n')
cat('varaince of x is ',var(x),'\n')
cat('standars deviation of x is ',sd(x),'\n')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 
mean of x is 8 
median of x is  8 
varaince of x is  20 
standars deviation of x is  4.472136 


In [70]:
x<-1:15
print(x)
print(paste('mean of x is',mean(x)))
print(paste('median of x is',median(x)))
print(paste('varaince of x is',var(x)))
print(paste('standard deviation of x is',sd(x)))

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15
[1] "mean of x is 8"
[1] "median of x is 8"
[1] "varaince of x is 20"
[1] "standard deviation of x is 4.47213595499958"


In [18]:
x<-8+7
x

[1] 15

In [19]:
x<-"dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] "dataset"

[1] "character"

[1] "character"

[1] 1

NULL

In [20]:
x<-23
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "numeric"

[1] "double"

[1] 1

NULL

In [21]:
x<-23L
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "integer"

[1] "integer"

[1] 1

NULL

In [22]:
x<-2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 2+3i

[1] "complex"

[1] "complex"

[1] 1

NULL

In [24]:
vector()

logical(0)

In [25]:
vector("character",length=5)

[1] "" "" "" "" ""

character(5)

In [27]:
numeric(5)
logical(5)

[1] 0 0 0 0 0

[1] FALSE FALSE FALSE FALSE FALSE

In [29]:
x<-c(12,55,34,23,01)
x
class(x)

[1] 12 55 34 23  1

[1] "numeric"

In [30]:
x<-c(12L,55L,34L,23L,01L)


[1] 12 55 34 23  1

[1] "integer"

[1] 5

In [31]:
x<-c(TRUE,FALSE,FALSE,TRUE,TRUE)
x
class(x)
length(x)

[1]  TRUE FALSE FALSE  TRUE  TRUE

[1] "logical"

[1] 5

In [32]:
z<-c("sarah","zen","shirayuki")
z
class(z)
length(z)

[1] "sarah"     "zen"       "shirayuki"

[1] "character"

[1] 3

In [33]:
#add elements at the add
print("elements in z before")
z
z<-c(z,"Annete")
print("elements in z after adding new element")
z

[1] "elements in z before"


[1] "sarah"     "zen"       "shirayuki"

[1] "elements in z after adding new element"


[1] "sarah"     "zen"       "shirayuki" "Annete"

In [34]:
a<-1:10
seq(10)
seq(from=1, to=10, by=0.1)

[1]  1  2  3  4  5  6  7  8  9 10

[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

In [35]:
1/0
0/0

[1] Inf

[1] NaN

In [36]:
exp(Inf)

[1] Inf

In [37]:
exp(-Inf)

[1] 0

In [38]:
Inf-Inf

[1] NaN

In [39]:
log(0)
log(1)

[1] -Inf

[1] 0

In [40]:
a<-c(1.7,"a")
a

[1] "1.7" "a"

In [43]:
b<-c(TRUE,2,3,FALSE)
b

[1] 1 2 3 0

In [45]:
c<-c("a",TRUE)
c

[1] "a"    "TRUE"

In [46]:
as.numeric("1")


[1] 1

In [50]:
as.numeric(c("45","55"))


[1] 45 55

In [51]:
as.numeric(c("45","55",'six'))

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] 45 55 NA

In [52]:
as.character(22)

[1] "22"

In [53]:
as.character(c(22,55,12))

[1] "22" "55" "12"

In [55]:
#matrix
m<-matrix(nrow=2,ncol=2)
m

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

In [56]:
dim(m)

[1] 2 2

In [59]:
class(m)
typeof(m)

[1] "matrix"

[1] "logical"

In [61]:
m<-matrix(c(1:3))
print("given matrix is")
print(m)
print("given dimensions is")
print(dim(m))
print('class of given matrix is')
print(class(m))
print('type of given matrix is')
print(typeof(m))

[1] "given matrix is"
     [,1]
[1,]    1
[2,]    2
[3,]    3
[1] "given dimensions is"
[1] 3 1
[1] "class of given matrix is"
[1] "matrix"
[1] "type of given matrix is"
[1] "integer"


In [62]:
a<-matrix(1:6,nrow=2,ncol=3)
a

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [65]:
m<-1:10
print(m)
print(dim(m))
dim(m)<-c(2,5)
print(m)
print(dim(m))

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


In [67]:
my_name<-readline(prompt='enter name:')
my_age<-readline(prompt='enter age:')
my_age<-as.integer(my_age)
print(paste('HI',my_name,'next year will be',my_age+1,'years old'))

enter name:chitti
enter age:18
[1] "HI chitti next year will be 19 years old"
